CREATE TABLE DEFAULT_SCHEMA.ACABADO (
       ID INT NOT NULL IDENTITY PRIMARY KEY
     , NOMBRE CHAR(50)
     , FACTOR DOUBLE
);

CREATE TABLE DEFAULT_SCHEMA.BASES (
       IDB INT NOT NULL IDENTITY PRIMARY KEY
     , NOMBRE CHAR(50)
);

CREATE TABLE DEFAULT_SCHEMA.PORCENTAJES (
       PORCENTAJE DOUBLE DEFAULT '0' NOT NULL
     , PRIMARY KEY (PORCENTAJE)
);

CREATE TABLE DEFAULT_SCHEMA.PRODUCTO (
       Id INT NOT NULL IDENTITY PRIMARY KEY
     , NOMBRE CHAR(50)
     , FACTOR DOUBLE
);

CREATE TABLE DEFAULT_SCHEMA.PIGMENTO (
       IDP INT NOT NULL IDENTITY PRIMARY KEY
     , NOMBRE CHAR(50)
     , CONSTRAINT FK_PIGMENTO_1 FOREIGN KEY (IDP)
                  REFERENCES DEFAULT_SCHEMA.PIGMENTO (IDP)
     , CONSTRAINT FK_PIGMENTO_2 FOREIGN KEY (IDP)
                  REFERENCES DEFAULT_SCHEMA.PIGMENTO (IDP)
);

CREATE TABLE DEFAULT_SCHEMA.BASES_PIGMENTO (
       PORCENTAJE DOUBLE
     , IDP INT NOT NULL
     , IDB INT NOT NULL
     , PRIMARY KEY (IDP, IDB)
     , CONSTRAINT FK_BASES_PIGMENTO_1 FOREIGN KEY (IDP, IDB)
                  REFERENCES DEFAULT_SCHEMA.BASES_PIGMENTO (IDP, IDB)
     , CONSTRAINT FK_BASES_PIGMENTO_2 FOREIGN KEY (IDP)
                  REFERENCES DEFAULT_SCHEMA.PIGMENTO (IDP)
     , CONSTRAINT FK_BASES_PIGMENTO_3 FOREIGN KEY (IDB)
                  REFERENCES DEFAULT_SCHEMA.BASES (IDB)
     , CONSTRAINT FK_BASES_PIGMENTO_4 FOREIGN KEY (IDP, IDB)
                  REFERENCES DEFAULT_SCHEMA.BASES_PIGMENTO (IDP, IDB)
     , CONSTRAINT FK_BASES_PIGMENTO_5 FOREIGN KEY (IDP, IDB)
                  REFERENCES DEFAULT_SCHEMA.BASES_PIGMENTO (IDP, IDB)
);

CREATE TABLE DEFAULT_SCHEMA.ADITIVOS (
       TOTAL_AGUA DOUBLE DEFAULT '0'
     , DISPERTANTE DOUBLE DEFAULT '0'
     , ANTIESPUMANTE DOUBLE DEFAULT '0'
     , NEGRO DOUBLE DEFAULT '0'
     , ESPESANTE DOUBLE DEFAULT '0'
     , MICREX DOUBLE DEFAULT '0'
     , MPEG DOUBLE DEFAULT '0'
     , PORCENTAJE DOUBLE DEFAULT '0' NOT NULL
     , IdB INT NOT NULL
     , PRIMARY KEY (PORCENTAJE, IdB)
     , CONSTRAINT FK_ADITIVOS_1 FOREIGN KEY (PORCENTAJE)
                  REFERENCES DEFAULT_SCHEMA.PORCENTAJES (PORCENTAJE)
     , CONSTRAINT FK_ADITIVOS_2 FOREIGN KEY (IdB)
                  REFERENCES DEFAULT_SCHEMA.BASES (IDB)
     , CONSTRAINT FK_ADITIVOS_3 FOREIGN KEY (PORCENTAJE, IdB)
                  REFERENCES DEFAULT_SCHEMA.ADITIVOS (PORCENTAJE, IdB)
);

