CREATE TABLE DEFAULT_SCHEMA.BASES_PIGMENTO (
       PORCENTAJE DOUBLE
     , IDP INT NOT NULL
     , IDB INT NOT NULL
     , PRIMARY KEY (IDP, IDB)
     , CONSTRAINT FK_BASES_PIGMENTO_1 FOREIGN KEY (IDP, IDB)
                  REFERENCES DEFAULT_SCHEMA.BASES_PIGMENTO (IDP, IDB)
     , CONSTRAINT FK_BASES_PIGMENTO_2 FOREIGN KEY (IDP)
                  REFERENCES DEFAULT_SCHEMA.PIGMENTO (IDP)
     , CONSTRAINT FK_BASES_PIGMENTO_3 FOREIGN KEY (IDB)
                  REFERENCES DEFAULT_SCHEMA.BASES (IDB)
     , CONSTRAINT FK_BASES_PIGMENTO_4 FOREIGN KEY (IDP, IDB)
                  REFERENCES DEFAULT_SCHEMA.BASES_PIGMENTO (IDP, IDB)
     , CONSTRAINT FK_BASES_PIGMENTO_5 FOREIGN KEY (IDP, IDB)
                  REFERENCES DEFAULT_SCHEMA.BASES_PIGMENTO (IDP, IDB)
);

