CREATE TABLE DEFAULT_SCHEMA.ACABADO (
       ID INT NOT NULL IDENTITY PRIMARY KEY
     , NOMBRE CHAR(50)
     , FACTOR DOUBLE
);

CREATE TABLE DEFAULT_SCHEMA.PIGMENTO (
       IDP INT NOT NULL IDENTITY PRIMARY KEY
     , NOMBRE CHAR(50)
);

CREATE TABLE DEFAULT_SCHEMA.BASES (
       IDB INT NOT NULL IDENTITY PRIMARY KEY
     , NOMBRE CHAR(50)
);

CREATE TABLE DEFAULT_SCHEMA.PORCENTAJES (
       PORCENTAJE DOUBLE DEFAULT '0' NOT NULL
     , PRIMARY KEY (PORCENTAJE)
);

CREATE TABLE DEFAULT_SCHEMA.ADITIVOS (
       NOMBRE CHAR(50) NOT NULL
     , PRIMARY KEY (NOMBRE)
);

CREATE TABLE DEFAULT_SCHEMA.PRODUCTO (
       Id INT NOT NULL IDENTITY PRIMARY KEY
     , NOMBRE CHAR(50)
     , FACTOR DOUBLE
);

CREATE TABLE DEFAULT_SCHEMA.BASE_PORCENTAJE (
       PORCENTAJE DOUBLE DEFAULT '0' NOT NULL
     , IdB INT NOT NULL
     , PRIMARY KEY (PORCENTAJE, IdB)
     , CONSTRAINT FK_ADITIVOS_1 FOREIGN KEY (PORCENTAJE)
                  REFERENCES DEFAULT_SCHEMA.PORCENTAJES (PORCENTAJE)
     , CONSTRAINT FK_ADITIVOS_2 FOREIGN KEY (IdB)
                  REFERENCES DEFAULT_SCHEMA.BASES (IDB)
);

CREATE TABLE DEFAULT_SCHEMA.BASES_PIGMENTO (
       PORCENTAJE DOUBLE
     , IDP INT NOT NULL
     , IDB INT NOT NULL
     , PRIMARY KEY (IDP, IDB)
     , CONSTRAINT FK_BASES_PIGMENTO_2 FOREIGN KEY (IDP)
                  REFERENCES DEFAULT_SCHEMA.PIGMENTO (IDP)
     , CONSTRAINT FK_BASES_PIGMENTO_3 FOREIGN KEY (IDB)
                  REFERENCES DEFAULT_SCHEMA.BASES (IDB)
);

CREATE TABLE DEFAULT_SCHEMA.ADITIVOS_CANTIDAD (
       CANTIDAD DOUBLE NOT NULL
     , NOMBRE CHAR(50) NOT NULL
     , PORCENTAJE DOUBLE DEFAULT '0' NOT NULL
     , IdB INT NOT NULL
     , PRIMARY KEY (NOMBRE, PORCENTAJE, IdB)
     , CONSTRAINT FK_ADITIVOS_CANTIDAD_1 FOREIGN KEY (NOMBRE)
                  REFERENCES DEFAULT_SCHEMA.ADITIVOS (NOMBRE)
     , CONSTRAINT FK_ADITIVOS_CANTIDAD_2 FOREIGN KEY (PORCENTAJE, IdB)
                  REFERENCES DEFAULT_SCHEMA.BASE_PORCENTAJE (PORCENTAJE, IdB)
);

